name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20' # change to '14' only if your app requires it

      - name: Install dependencies
        if: ${{ hashFiles('package.json') != '' }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run build --if-present

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'copilot-webapp-demo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
