name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: app

      - name: Build
        run: npm run build --if-present
        working-directory: app

      - name: Archive app
        run: |
          zip -r ../release.zip .
        working-directory: app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: copilot-webapp-demo
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
